### PR TITLE
mruby 3.0 compatibility

### PR DESCRIPTION
**Pull request by palkan**
Use integer_class instead of fixnum_class for mruby 3.0+.
Also renamed internal functions to use integer instead of fixnum.

### CODE REVIEW

**Comment by Asmod4n** [comment]
Looks good, thanks.

The constants haven’t been renamed and mrb_fixnum_p still exists?

**Comment by palkan** [comment]
> The constants haven’t been renamed and mrb_fixnum_p still exists?

Yeah: https://github.com/mruby/mruby/blob/6d3c0227498050d551243417340e704023fcaf42/include/mruby/boxing_no.h#L34

`mrb_integer` has also been added though, but supporting both 2 and 3 would be tricky; unless we do something like this: https://github.com/mruby/mruby/blob/1d0cfb359c5a0c482c25e5fada987148738012ad/include/mruby/value.h#L210-L212

Not sure that's OK for a library.

**Comment by Asmod4n** [comment]
Ok, it’s merged.

**Comment by palkan** [comment]
Thanks!

**Pull request merged**
